homefinder/homefinder/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from homesapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'homesapp/',include('homesapp.urls')),
    path(r'', views.test_redirect, name='test_redirect'),
]

homefinder/homesapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth.views import LoginView
from .import views

urlpatterns = [
    #/homesapp/
    url(r'^$',views.IndexView.as_view(),name='index'),
   #/homesapp/1
   url(r'^(?P<pk>[0-9]+)/$',views.LocationView.as_view(),name='property'),
   #/homesapp/1/2
    url(r'^([0-9]+)/(?P<pk>[0-9]+)/$',views.PropertyDetail.as_view(),name='propertyview'),
    url(r'^signup/$',views.signup_view,name="signup"),
    url(r'^home/',views.home_view,name="home"),
    url(r'^login/$',views.login_view,name="login")
]

homefinder/homesapp/models.py
from django.db import models

# Create your models here.

class Location(models.Model):
    location_name = models.CharField(max_length = 200)
    location_type = models.CharField(max_length = 200)

    def __str__(self):
        return self.location_name


class Property(models.Model):
    location = models.ForeignKey(Location,on_delete = models.CASCADE)
    property_name = models.CharField(max_length = 200)
    area = models.CharField(max_length = 200)

    age = models.CharField(max_length = 200)
    price = models.CharField(max_length = 200)
    direction = models.CharField(max_length = 200)
    floor = models.CharField(max_length = 200)
    postaladd = models.CharField(max_length = 200)
    image_url = models.CharField(max_length = 500)
    lat_field = models.CharField(max_length = 200)
    long_field = models.CharField(max_length = 200)

    owner_name = models.CharField(max_length = 200)
    owner_phone = models.CharField(max_length = 200)
    owner_emailid = models.CharField(max_length = 200)

    def __str__(self):
        return self.property_name

    



    

homefinder/homesapp/views.py
from django.shortcuts import render,redirect
from django.views import generic
from .models import Location
from .models import Property
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login
from django.http import HttpResponse, HttpResponseNotFound, Http404,  HttpResponseRedirect
from django.shortcuts import redirect

# Create your views here.
 
def test_redirect(request):
    return redirect('/homesapp/home')

class IndexView(generic.ListView):
    template_name = 'homesapp/index.html'

    def get_queryset(self):
        return Location.objects.all()

class LocationView(generic.DetailView):
    model =  Location
    template_name = 'homesapp/locationview.html'

class PropertyDetail(generic.DetailView):
    model = Property
    template_name = 'homesapp/propertyview.html'


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log user in
            login(request,user)
            return redirect('/homesapp/')
    else:
        form = UserCreationForm()
    return render(request,'homesapp/signup.html',{'form':form})

def home_view(request):
    return render(request,'homesapp/home.html')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #login the user
            user = form.get_user()
            login(request,user)
            return redirect('/homesapp/')
    else:
        form = AuthenticationForm()
    return render(request,'homesapp/login.html',{'form':form})

 
    

homefinder/homesapp/templates/homesapp/base.html
<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
        body {
            background-color : lightblue;
        }
        </style>
</head>
<body>
    <nav class = "navbar navbar-inverse">
        <div class ="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Property Arena</a>
            </div>

            <ul class="nav navbar-nav">
                <li class="active"><a href="/homesapp/">Home</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/homesapp/home/"</a>Logout</a></li>
            </ul>

        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>

</html>

homefinder/homesapp/templates/homesapp/base1.html
<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
        body {
            background-color : lightblue;
        }
        </style>
</head>
<body>
    <nav class = "navbar navbar-inverse">
        <div class ="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Property Arena</a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/homesapp/login"</a>Login</a></li>
            </ul>

        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>

</html>

homefinder/homesapp/templates/homesapp/base2.html
<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
        body {
            background-color:lightblue;
        }
        </style>
</head>
<body>
    <nav class = "navbar navbar-inverse">
        <div class ="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Property Arena</a>
            </div>

        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>

</html>

homefinder/homesapp/templates/homesapp/home.html
{% extends 'homesapp/base2.html' %}
{% load static %}
<html>
    <head></head>
        {% block body %}
        <body>
            <div class="container">
                <div class="container">
                    <div class="jumbotron">
                        <center><h1>Property Arena</h1></center>
                    </div>
            </div>
                <center><h1>Signup into the Property Arena </h1></center>
                <center><a href="/homesapp/signup" style="background-color:white; display:inline-block; padding: 15px 32px; border: solid black 1px;">Signup</a></center>
                 <br>
                 <br>
                 <br>
                 <br>
                <center><h1>Login to the Property Arena </h1></center>
                <center><a href="/homesapp/login" style="background-color:white; display:inline-block; padding: 15px 32px; border: solid black 1px;">Login</a></center>
        </body>
        {% endblock %}
</html>

homefinder/homesapp/templates/homesapp/index.html
{% extends 'homesapp/base.html' %}
<html>
    <head></head>
        {% block body %}
        <body>
            <div class="container">
                <div class="container">
                    <div class="jumbotron">
                        <h1>Property Areana</h1>
                        <p>Find the Best Properties across all locations</p>
                    </div>
            </div>

            <centre><h1>Select your locations</h1></centre>
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">Locations</div>
                    {% for location in object_list %}
                    <div class="panel-body"><a href="/homesapp/{{location.id}}">{{location.location_name}}</a></div>
                    {% endfor %}
                </div>
            </div>
        </body>
        {% endblock %}
</html>>

homefinder/homesapp/templates/homesapp/locationview.html
{% extends 'homesapp/base.html' %}

{% block body  %}

<html>
    <head></head>
    <body>
        <div class="col-md-1">
        </div>
        <div class="col-md-8">
            <h1>Properties in {{location.location_name}}</h1>
            <div class ="panel-group">
                {% for place in location.property_set.all %}
                <div class ="panel panel-primary">
                    <div class="panel-heading">{{place.property_name}}</div>
                    <div class="panel-body">
                        <div class="col-md-4">
                            <img src="{{place.image_url}}" height="200" width="200">
                        </div>
                        <div class="col-md-6">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td><label><b>Area SQFT</b></label></td>
                                        <td>{{place.area}}</td>
                                    </tr>
                                    <tr>
                                            <td><label><b>Price</b></label></td>
                                            <td>{{place.price}}</td>
                                    </tr>
                                    <tr>
                                            <td><label><b>No of Floors</b></label></td>
                                            <td>{{place.floor}}</td>
                                    </tr>
                                    <tr>
                                            <td><label><b>Address</b></label></td>
                                            <td>{{place.postaladd}}</td>
                                    </tr>
                                    <tr>
                                        <td>   
                                        </td>
                                        <td>
                                        </td>
                                        <td><a class="btn btn-sucess" href="/homesapp/{{location.id}}/{{place.id}}" style="background-color:white; display:inline-block; padding: 15px 32px; border: solid black 1px;">View Details</a></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

    </body>
</html>

{% endblock %}

homefinder/homesapp/templates/homesapp/login.html
{% extends 'homesapp/base2.html' %}

{%block body%}
    <h1>Login</h1>
    <form class="site-form" action="/homesapp/login/" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Login">
    </form>

{%endblock%}

homefinder/homesapp/templates/homesapp/propertyview.html
{% extends 'homesapp/base.html' %}

{% block body  %}

<html>

    <head>
        <style>
                    
         #map {
                height: 100%;  
                width: 100%;  
                }
        html,body{
            text-align: center;
            height:75%;
            width: 100%;
            margin: 0;
            padding:0;
        }
        </style>
    </head>

    <body>
        <div class="row">
            <div class="col-md-1">
            </div>

            <div class="col-md-5">
                <div class="thumbnail">
                    <img src="{{property.image_url}}" height="420" widht="420">
                    <div class ="caption">
                        <p>{{property.property_name}}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-5">
                    <div class ="panel-group">
                        <div class="panel panel-primary">
                            <div class="panel-heading">Property Details</div>
                            <div class="panel-body">
                                <table class="table">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label><b> Area SQFT </b></label>
                                            </td>
                                            <td>
                                                {{property.area}}
                                            </td>
                                        </tr>
                                        <tr>
                                                <td>
                                                    <label><b>Price</b></label>
                                                </td>
                                                <td>
                                                    {{property.price}}
                                                </td>
                                        </tr>
                                        <tr>
                                                <td>
                                                    <label><b>Age</b></label>
                                                </td>
                                                <td>
                                                    {{property.age}}
                                                </td>
                                        </tr>
                                        <tr>
                                                <td>
                                                    <label><b>Direction</b></label>
                                                </td>
                                                <td>
                                                    {{property.direction}}
                                                </td>
                                        </tr>
                                        <tr>
                                                <td>
                                                    <label><b>No of Floors</b></label>
                                                </td>
                                                <td>
                                                    {{property.floor}}
                                                </td>
                                        </tr>
                                        <tr>
                                                <td>
                                                    <label><b>Address </b></label>
                                                </td>
                                                <td>
                                                    {{property.postaladd}}
                                                </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
        </div>

<!-- Map Starts Here -->
        <div class="col-md-7">
            <div class="thumbnail">
                <h3>Location</h3>
                <div id="map"></div>
                    <script>
                    function initMap() { 
                        var uluru = {lat:{{property.lat_field}}, lng:{{property.long_field}}};
                    var map = new google.maps.Map(document.getElementById('map'), {zoom: 20, center: uluru});
                    var marker = new google.maps.Marker({position: uluru, map: map});
                    }
                    </script>
                <script async defer
                    src="Google Maps API Key to be inserted in here">
                </script>    
            </div>
        </div>
        <div class="col-md-5">
                        <div class="panel-group">
                            <div class= "panel panel-primary">
                                <div class ="panel-heading">Owner Details</div>
                                <div class ="panel-body">
                                                <table class="table">
                                                    <tbody>
                                                        <tr>
                                                            <td>
                                                                <label><b> Owner Name </b></label>
                                                            </td>
                                                            <td>
                                                                {{property.owner_name}}
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                                <td>
                                                                    <label><b> Owner Contact </b></label>
                                                                </td>
                                                                <td>
                                                                    {{property.owner_phone}}
                                                                </td>
                                                        </tr> 
                                                        <tr>
                                                                <td>
                                                                    <label><b> Owner Email </b></label>
                                                                </td>
                                                                <td>
                                                                    {{property.owner_emailid}}
                                                                </td>
                                                        </tr> 
                                                    </tbody>
                                                </table>
                                </div>
                                        
                                </div>
                            </div>
                        </div>
        </div>
    </body>
</html>

{% endblock %}

homefinder/homesapp/templates/homesapp/signup.html
{% extends 'homesapp/base1.html' %}

{%block body%}
    <h1>Sign-Up</h1>
    <form class="site-form" action="/homesapp/signup/" method="post" 
    style=" margin-top:20px;
    border: 1px solid #00dba0; 
    display: block;
    padding: 40px;"
    >
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Signup">
    </form>

{%endblock%}